"""Stage 9 派生统计与 hash 绑定报告。"""

from .charts import ChartArtifact, ChartSpec, render_matplotlib_chart
from .metrics import (
    MetricResult,
    bias,
    damage_auc,
    effective_parameter_count,
    entropy,
    error_summary,
    gini,
    hhi,
    mae,
    mean_confidence_interval,
    mean_squared_bias,
    mse,
    pearson,
    spearman,
    top_k_jaccard,
    top_k_overlap,
    top_q_mass,
    variance,
)
from .report import (
    AnalysisReport,
    AnalysisReportBuilder,
    FrozenSourceTable,
    MetricSourceBinding,
    SourceArtifact,
)
from .pipeline import (
    AnalysisBundle,
    AnalysisBundleBuilder,
    BoundSourceTable,
    CompositeFigureArtifact,
    CrossStageSourceBuilder,
    HeatmapArtifact,
    HeatmapSpec,
    StageArtifactRows,
    TableArtifact,
    TableSpec,
    grouped_statistics,
    analysis_producer_source_hash,
    paired_statistics_with_holm,
    render_heatmap,
    render_composite_figure_set,
    render_table,
)
from .index import DerivedTableIndex

__all__ = [
    "MetricResult",
    "MetricSourceBinding",
    "AnalysisReport",
    "AnalysisReportBuilder",
    "AnalysisBundle",
    "AnalysisBundleBuilder",
    "BoundSourceTable",
    "CompositeFigureArtifact",
    "ChartArtifact",
    "ChartSpec",
    "FrozenSourceTable",
    "CrossStageSourceBuilder",
    "DerivedTableIndex",
    "HeatmapArtifact",
    "HeatmapSpec",
    "SourceArtifact",
    "StageArtifactRows",
    "TableArtifact",
    "TableSpec",
    "bias",
    "damage_auc",
    "effective_parameter_count",
    "entropy",
    "error_summary",
    "gini",
    "hhi",
    "mae",
    "mean_confidence_interval",
    "mean_squared_bias",
    "mse",
    "pearson",
    "spearman",
    "top_k_jaccard",
    "top_k_overlap",
    "top_q_mass",
    "variance",
    "grouped_statistics",
    "analysis_producer_source_hash",
    "paired_statistics_with_holm",
    "render_heatmap",
    "render_composite_figure_set",
    "render_table",
    "render_matplotlib_chart",
]
