"""Stage 9 派生统计与 hash 绑定报告。"""

from .charts import ChartArtifact, ChartSpec, render_matplotlib_chart
from .metrics import (
    MetricResult,
    bias,
    damage_auc,
    effective_parameter_count,
    entropy,
    error_summary,
    gini,
    hhi,
    mae,
    mean_confidence_interval,
    mean_squared_bias,
    mse,
    pearson,
    spearman,
    top_k_jaccard,
    top_k_overlap,
    top_q_mass,
    variance,
)
from .report import (
    AnalysisReport,
    AnalysisReportBuilder,
    FrozenSourceTable,
    MetricSourceBinding,
    SourceArtifact,
)

__all__ = [
    "MetricResult",
    "MetricSourceBinding",
    "AnalysisReport",
    "AnalysisReportBuilder",
    "ChartArtifact",
    "ChartSpec",
    "FrozenSourceTable",
    "SourceArtifact",
    "bias",
    "damage_auc",
    "effective_parameter_count",
    "entropy",
    "error_summary",
    "gini",
    "hhi",
    "mae",
    "mean_confidence_interval",
    "mean_squared_bias",
    "mse",
    "pearson",
    "spearman",
    "top_k_jaccard",
    "top_k_overlap",
    "top_q_mass",
    "variance",
    "render_matplotlib_chart",
]
