"""参数重要性项目 Stage 0–9 的共享合同公共入口。

该包只定义数据、身份、状态和资格规则，不依赖训练、实验或分析实现，因此其余分区
可以单向依赖这里。业务模块应从本入口导入公开类型；具体编码辅助函数仍按需从
``jsonio`` 导入，避免把 legacy 兼容误当成普通运行时路径。
"""

from .config import (
    CONFIG_SCHEMA_VERSION,
    CONFIG_SECTIONS,
    ConfigDifference,
    ResolvedConfig,
    diff_configs,
    strict_merge,
)
from .config_v2 import (
    CONFIG_V2_SCHEMA_VERSION,
    ResolvedConfigV2,
    load_resolved_config_compatible,
)
from .artifacts import (
    ValidatedArtifact,
    validate_estimator_decision_artifact,
    validate_path_integral_result_artifact,
    validate_path_spec_artifact,
    validate_reference_result_artifact,
)
from .errors import (
    CanonicalJSONError,
    ConfigContractError,
    ContractError,
    DependencyUnavailable,
    FormalRunRejected,
    FreezeContractError,
    GateContractError,
    IdentityContractError,
    ProvenanceContractError,
    SeedContractError,
)
from .freeze import ContractFreeze
from .identity import RunIdentity, derive_experiment_id
from .jsonio import (
    JSONScalar,
    JSONValue,
    canonical_json_bytes,
    canonical_json_hash,
    ensure_json_object,
    import_legacy_json,
    load_canonical_json,
    loads_strict_json,
    write_canonical_json,
)
from .provenance import ProvenanceRecord, ProvenanceStatus
from .readiness import (
    FormalReadiness,
    evaluate_formal_readiness,
    require_formal_readiness,
)
from .review import (
    ARTIFACT_APPROVAL_SCHEMA_VERSION,
    ARTIFACT_REVIEW_SCHEMA_VERSION,
    ApprovalScope,
    ArtifactApproval,
    ArtifactReview,
    ArtifactReviewError,
    ReviewDecision,
)
from .runtime_evidence import RuntimeCapabilityEvidence, RuntimeEvidenceError
from .seed import (
    DEFAULT_SEED_DOMAINS,
    SEED_ALGORITHM_VERSION,
    SeedPlan,
    derive_seed,
)
from .status import (
    ContractState,
    GateRecord,
    GateStatus,
    LocalValidationRecord,
    LocalValidationStatus,
    validate_gate_id,
)
from .stage23 import (
    ArtifactQualification,
    FormalExecutionEvidence,
    require_accepted_gate,
    validate_stage23_artifact,
)
from .task_catalog import (
    DEFAULT_TASK_CATALOG,
    RESOLVED_CONFIG_V2_SCHEMA_REF,
    TASK_CATALOG_SCHEMA_VERSION,
    TASK_DEFINITION_SCHEMA_VERSION,
    TASK_OUTPUT_ARTIFACT_SCHEMA_REF,
    TASK_OUTPUT_PAYLOAD_SCHEMA_REF,
    TASK_OUTPUT_COMMIT_SCHEMA_REF,
    ExistingOutputPolicy,
    FormalEligibilityPolicy,
    InputArtifactContract,
    LocalFixturePolicy,
    OutputArtifactContract,
    RecoveryMode,
    ReplayPolicy,
    ReplayStrategy,
    RunnerKind,
    SafeBoundary,
    StageTaskCatalog,
    TaskCatalog,
    TaskCatalogError,
    TaskDefinition,
)

__all__ = [
    "CONFIG_SCHEMA_VERSION",
    "CONFIG_V2_SCHEMA_VERSION",
    "CONFIG_SECTIONS",
    "ARTIFACT_APPROVAL_SCHEMA_VERSION",
    "ARTIFACT_REVIEW_SCHEMA_VERSION",
    "DEFAULT_SEED_DOMAINS",
    "DEFAULT_TASK_CATALOG",
    "RESOLVED_CONFIG_V2_SCHEMA_REF",
    "SEED_ALGORITHM_VERSION",
    "CanonicalJSONError",
    "ApprovalScope",
    "ArtifactApproval",
    "ArtifactReview",
    "ArtifactReviewError",
    "ArtifactQualification",
    "ConfigContractError",
    "ConfigDifference",
    "ContractError",
    "DependencyUnavailable",
    "ContractFreeze",
    "ContractState",
    "FormalReadiness",
    "FormalExecutionEvidence",
    "FormalEligibilityPolicy",
    "ExistingOutputPolicy",
    "InputArtifactContract",
    "LocalFixturePolicy",
    "OutputArtifactContract",
    "FormalRunRejected",
    "FreezeContractError",
    "GateContractError",
    "GateRecord",
    "GateStatus",
    "IdentityContractError",
    "JSONScalar",
    "JSONValue",
    "LocalValidationRecord",
    "LocalValidationStatus",
    "ProvenanceContractError",
    "ProvenanceRecord",
    "ProvenanceStatus",
    "ResolvedConfig",
    "ResolvedConfigV2",
    "ReviewDecision",
    "RuntimeCapabilityEvidence",
    "RuntimeEvidenceError",
    "RecoveryMode",
    "RunnerKind",
    "RunIdentity",
    "SeedContractError",
    "SeedPlan",
    "SafeBoundary",
    "StageTaskCatalog",
    "TASK_CATALOG_SCHEMA_VERSION",
    "TASK_DEFINITION_SCHEMA_VERSION",
    "TASK_OUTPUT_ARTIFACT_SCHEMA_REF",
    "TASK_OUTPUT_PAYLOAD_SCHEMA_REF",
    "TASK_OUTPUT_COMMIT_SCHEMA_REF",
    "ReplayPolicy",
    "ReplayStrategy",
    "TaskCatalog",
    "TaskCatalogError",
    "TaskDefinition",
    "ValidatedArtifact",
    "canonical_json_bytes",
    "canonical_json_hash",
    "derive_experiment_id",
    "derive_seed",
    "diff_configs",
    "ensure_json_object",
    "evaluate_formal_readiness",
    "import_legacy_json",
    "load_canonical_json",
    "loads_strict_json",
    "load_resolved_config_compatible",
    "require_formal_readiness",
    "require_accepted_gate",
    "strict_merge",
    "validate_path_integral_result_artifact",
    "validate_estimator_decision_artifact",
    "validate_path_spec_artifact",
    "validate_reference_result_artifact",
    "validate_stage23_artifact",
    "validate_gate_id",
    "write_canonical_json",
]
