"""运行时层：事件、张量产物、checkpoint、归约和优化器事务。"""

from .checkpoint import (
    CheckpointCommit,
    CheckpointRetentionApplication,
    CheckpointRetentionPolicy,
    CheckpointRetentionSelection,
    CheckpointStore,
)
from .events import (
    EventRecord,
    EventSink,
    EventType,
    JsonlEventSink,
    canonical_optimizer_steps,
    read_event_stream,
)
from .distributed_training import DistributedLaunchSpec, TorchDDPTrainingExecutor
from .gradients import GradientAttempt, GradientPhase
from .lineage import AttemptDisposition, AttemptLineageRecord, LineageStore
from .optimizer import OptimizerBridge, StepOutcome, compute_global_clip_factor
from .process_state import ProcessSnapshot, ProcessStateStore
from .reducers import (
    LocalReducer,
    Reducer,
    ReducerCapabilities,
    TorchDistributedReducer,
)
from .tensor_bundle import TensorBundle, load_tensor_bundle, publish_tensor_bundle
from .telemetry import ResourceProfile, ResourceSampler, rebuild_tensorboard_from_jsonl
from .transactions import StepPhase, StepTransaction
from .task_runtime import (
    TASK_RUNTIME_ENVIRONMENT_SCHEMA_VERSION,
    BlockerCode,
    TaskBlockedError,
    TaskBlocker,
    TaskExecutionRequest,
    TaskResult,
    TaskRunResult,
    TaskRunSpec,
    TaskRunStatus,
    TaskRunner,
    TaskRuntime,
    TaskRuntimeEnvironment,
    TaskRuntimeError,
)
from .task_artifacts import (
    LoadedTaskArtifact,
    PublishedTaskArtifact,
    TaskArtifactStore,
    load_committed_task_artifact,
)
from .task_lifecycle import (
    TASK_FINALIZATION_SCHEMA_VERSION,
    TASK_REPLAY_SCHEMA_VERSION,
    TASK_STATUS_SCHEMA_VERSION,
    TaskFinalizationRecord,
    TaskLifecycleError,
    TaskReplayRecord,
    TaskStatusSnapshot,
    load_task_run_result,
    logical_reference,
    publish_canonical_immutable,
)
from .training import (
    AttemptCommitEvent,
    GradientReadyEvent,
    ImportanceSnapshot,
    ImportanceTrajectory,
    ImportanceTrajectoryPoint,
    OnlineImportanceTracker,
    ParameterPostEvent,
    SkippedAttemptEvent,
    TrainingEngine,
    TrainingPhaseRunner,
    TrainingRunResult,
    TrainingRunSpec,
    TrainingState,
    TrainingStepRecord,
    TrainingStepObserver,
    install_training_rng,
)
from .training_factory import build_grad_scaler, build_optimizer, build_scheduler

__all__ = [
    "CheckpointCommit",
    "AttemptCommitEvent",
    "CheckpointRetentionApplication",
    "CheckpointRetentionPolicy",
    "CheckpointRetentionSelection",
    "CheckpointStore",
    "BlockerCode",
    "DistributedLaunchSpec",
    "AttemptDisposition",
    "AttemptLineageRecord",
    "EventRecord",
    "EventSink",
    "EventType",
    "GradientAttempt",
    "GradientReadyEvent",
    "GradientPhase",
    "ImportanceSnapshot",
    "ImportanceTrajectory",
    "ImportanceTrajectoryPoint",
    "JsonlEventSink",
    "LocalReducer",
    "LineageStore",
    "LoadedTaskArtifact",
    "OptimizerBridge",
    "OnlineImportanceTracker",
    "ParameterPostEvent",
    "SkippedAttemptEvent",
    "ProcessSnapshot",
    "ProcessStateStore",
    "PublishedTaskArtifact",
    "Reducer",
    "ReducerCapabilities",
    "ResourceProfile",
    "ResourceSampler",
    "StepOutcome",
    "StepPhase",
    "StepTransaction",
    "TensorBundle",
    "TASK_FINALIZATION_SCHEMA_VERSION",
    "TASK_REPLAY_SCHEMA_VERSION",
    "TASK_RUNTIME_ENVIRONMENT_SCHEMA_VERSION",
    "TASK_STATUS_SCHEMA_VERSION",
    "TaskBlockedError",
    "TaskArtifactStore",
    "TaskBlocker",
    "TaskExecutionRequest",
    "TaskFinalizationRecord",
    "TaskLifecycleError",
    "TaskReplayRecord",
    "TaskResult",
    "TaskRunResult",
    "TaskRunSpec",
    "TaskRunStatus",
    "TaskRunner",
    "TaskRuntime",
    "TaskRuntimeEnvironment",
    "TaskRuntimeError",
    "TaskStatusSnapshot",
    "TorchDistributedReducer",
    "TorchDDPTrainingExecutor",
    "TrainingEngine",
    "TrainingPhaseRunner",
    "TrainingRunResult",
    "TrainingRunSpec",
    "TrainingState",
    "TrainingStepRecord",
    "TrainingStepObserver",
    "install_training_rng",
    "canonical_optimizer_steps",
    "build_grad_scaler",
    "build_optimizer",
    "build_scheduler",
    "compute_global_clip_factor",
    "load_tensor_bundle",
    "load_committed_task_artifact",
    "load_task_run_result",
    "logical_reference",
    "publish_canonical_immutable",
    "publish_tensor_bundle",
    "read_event_stream",
    "rebuild_tensorboard_from_jsonl",
]
