"""参数重要性研究的纯数学核心公共 API。

该分区只依赖 Torch/NumPy（置信区间调用时可选 SciPy），不导入 runtime、模型
供应商或实验编排，因此可在 Windows CPU fixture 中独立验证。
"""

from .accumulator import ImportanceAccumulator
from .baselines import (
    BaselineProduction,
    cumulative_movement,
    empirical_fisher,
    final_magnitude,
    net_movement,
    produce_baseline_scores,
    synaptic_intelligence,
)
from .errors import CoreContractError, NumericalError, RegistryError, TensorMapError
from .estimators import (
    NO_UNBIASEDNESS_CLAIM,
    PLUGIN_SAME_BATCH_CLIP,
    UNBIASED_FIXED_STATE,
    EstimatorResult,
    cross_u_importance,
    double_sample_importance,
    equal_u_importance,
    global_clip_factor,
    raw_importance,
    weighted_u_importance,
)
from .losses import LossBatch, causal_lm_loss, sequence_classification_loss
from .metrics import (
    MetricResult,
    bias,
    confidence_interval,
    cosine_similarity,
    damage_auc,
    effective_parameter_count,
    entropy,
    gini_coefficient,
    hhi,
    mae,
    mse,
    normalized_l1_error,
    normalized_l2_error,
    normalized_linf_error,
    pearson_correlation,
    sign_agreement,
    spearman_correlation,
    top_k_jaccard,
    top_k_overlap,
    top_q_mass,
    variance,
)
from .oracles import (
    ConstantGradientFixture,
    FP64Comparison,
    QuadraticLossFixture,
    ZeroMeanNoiseFixture,
    central_difference_gradient,
    compare_tensor_maps_fp64,
    fp64_apply_group_learning_rates,
    fp64_cross_u_oracle,
    fp64_double_sample_oracle,
    fp64_equal_u_oracle,
    fp64_mean_gradient_oracle,
    fp64_raw_oracle,
    fp64_weighted_u_oracle,
)
from .pruning import (
    CoordinateSelection,
    PruningContext,
    PruningPlan,
    canonical_coordinate_id,
    select_pruned_coordinates,
)
from .quadrature import (
    PathIntegralResult,
    PathSpec,
    QuadratureRule,
    composite_left_rule,
    composite_midpoint_rule,
    composite_right_rule,
    composite_rule,
    composite_simpson_rule,
    composite_trapezoid_rule,
    default_quadrature_rules,
    gauss_legendre_rule,
    integrate_path,
    integrate_scalar_function,
    left_rule,
    midpoint_rule,
    right_rule,
    simpson_rule,
    trapezoid_rule,
)
from .registry import ParameterRecord, ParameterRegistry
from .sufficient_statistics import EqualSufficientStatistics, WeightedSufficientStatistics
from .tensors import TensorMap

__all__ = [
    "CoordinateSelection",
    "BaselineProduction",
    "ConstantGradientFixture",
    "CoreContractError",
    "EqualSufficientStatistics",
    "EstimatorResult",
    "FP64Comparison",
    "ImportanceAccumulator",
    "LossBatch",
    "MetricResult",
    "NO_UNBIASEDNESS_CLAIM",
    "NumericalError",
    "PLUGIN_SAME_BATCH_CLIP",
    "ParameterRecord",
    "ParameterRegistry",
    "PathIntegralResult",
    "PathSpec",
    "PruningContext",
    "PruningPlan",
    "QuadraticLossFixture",
    "QuadratureRule",
    "RegistryError",
    "TensorMap",
    "TensorMapError",
    "UNBIASED_FIXED_STATE",
    "WeightedSufficientStatistics",
    "ZeroMeanNoiseFixture",
    "bias",
    "canonical_coordinate_id",
    "causal_lm_loss",
    "central_difference_gradient",
    "composite_left_rule",
    "composite_midpoint_rule",
    "composite_right_rule",
    "composite_rule",
    "composite_simpson_rule",
    "composite_trapezoid_rule",
    "confidence_interval",
    "compare_tensor_maps_fp64",
    "cosine_similarity",
    "cumulative_movement",
    "cross_u_importance",
    "damage_auc",
    "default_quadrature_rules",
    "double_sample_importance",
    "effective_parameter_count",
    "empirical_fisher",
    "entropy",
    "equal_u_importance",
    "final_magnitude",
    "fp64_apply_group_learning_rates",
    "fp64_cross_u_oracle",
    "fp64_double_sample_oracle",
    "fp64_equal_u_oracle",
    "fp64_mean_gradient_oracle",
    "fp64_raw_oracle",
    "fp64_weighted_u_oracle",
    "gauss_legendre_rule",
    "gini_coefficient",
    "global_clip_factor",
    "hhi",
    "integrate_path",
    "integrate_scalar_function",
    "left_rule",
    "mae",
    "midpoint_rule",
    "mse",
    "normalized_l1_error",
    "normalized_l2_error",
    "normalized_linf_error",
    "net_movement",
    "pearson_correlation",
    "produce_baseline_scores",
    "raw_importance",
    "right_rule",
    "select_pruned_coordinates",
    "sequence_classification_loss",
    "sign_agreement",
    "simpson_rule",
    "spearman_correlation",
    "synaptic_intelligence",
    "top_k_jaccard",
    "top_k_overlap",
    "top_q_mass",
    "trapezoid_rule",
    "variance",
    "weighted_u_importance",
]
